server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wastemanagement?useSSL=false&serverTimezone=UTC
   # url: jdbc:sqlserver://wastedbb.database.windows.net:1433;database=wastedb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: root
   # username: AdminOla@wastedbbclea
    password: olatunbosun
   # password: Olatunbosun02@
    driver-class-name: com.mysql.cj.jdbc.Driver
   # driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
   # database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: password
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 6be7b0bd588d81
    password: 39c49cb87d598c
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
   # host: goose-01.rmq2.cloudamqp.com
    port: 5672
    username: myuser
   # username: gatgunnd
    password: mypassword
   # password: bY1VRqcDh9sicHsEeTkF50QpJvBIOQlr

jwt:
  secret: HGDeNsQr2wLct3lLxp6a9NjK2t5uHAaZ0djJMVNaOp4W2nwb3BVDV6bdvFrijr7M

application:
  mail:
    sent:
      from: no-reply@food.com
  security:
    jwt:
      secret-key: HGDeNsQr2wLct3lLxp6a9NjK2t5uHAaZ0djJMVNaOp4W2nwb3BVDV6bdvFrijr7M
      expiration: 86400000
      refresh-token:
        expiration: 604800000
  google:
    clientId: 106570000000000000000

rabbitmq:
  queue:
    email:
      name: email_queue
  exchange:
    email:
      name: email_exchange
  binding:
    email:
      name: email_routing_key

logging:
  level:
    org:
      springframework:
        transaction: DEBUG
        orm:
          jpa: DEBUG
